I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter2.rpy", line 333, in script
    jump chapter3
ScriptError: could not find label 'chapter3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter2.rpy", line 333, in script
    jump chapter3
  File "C:\RenPy\renpy-7.4.4-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\RenPy\renpy-7.4.4-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'chapter3'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
Rascals at Heart 1.0
Fri Jan  3 18:22:52 2025
